version: '2'
services:
  db:
    image: hypriot/rpi-mysql
    env_file:
      - MySQL.env
    volumes:
      - ./datadir:/var/lib/mysql
    restart: always
  web:
    build: .
    env_file:
      - MySQL.env
      - Shinobi.env
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ./config:/config
      - ./videos:/opt/shinobi/videos
    depends_on:
      - db
    ports:
      - "8080:8080"
    restart: always
  zigbee2mqtt:
    container_name: zigbee2mqtt
    image: koenkk/zigbee2mqtt:arm32v6
    volumes:
      - ./zigbee/data:/app/data
    devices:
      - /dev/ttyACM0:/dev/ttyACM0
    restart: always
